### ISSUE TITLE
Facebook bot makes request as soon as gem is required

### ISSUE THREAD

**Issue by yjukaku** [alaz/legitbot#7]
Hey, thanks for your work on this gem. I've noticed something while running test and I think it may require a change to the internals of Legitbot.

As it stands, legitbot will make actual web requests as soon as it's `require`d, even before any calls to `bot.valid?` are called, because the Facebook bot matcher loads `ValidIPs` in the class declaration. Is there any way around this?

**Comment by alaz** [comment]
Hello.

Suggestions?

**Comment by yjukaku** [comment]
We sometimes run tests without internet connection, but the entire suite fails to boot simply because Legitbot is in the Gemfile. We can't even get to a point where stubbing the `Legitbot` class would work, since the stub would run after the `Legitbot` class is required.

Maybe one solution could be to lazy-load the IPs. That way, the request is only made on the first `valid?` call to the `FacebookBot`. Or, add a requirement for a Rails initializer like:

```ruby
# in config/initializers/legitbot.rb
Legitbot.load_bots!
```
